# redis-values.yaml
architecture: standalone   # Режим standalone: один узел Redis (без реплик)
auth:
  enabled: false           # Отключить требование пароля (без авторизации)
# В результате Redis будет работать без пароля, любой под в кластере сможет подключиться.

# Опционально: настроим количество баз данных
master:
  configuration: |-
    databases 2
# ^ Эта настройка добавляет в конфигурацию Redis строку "databases 2",
# ограничивая число баз данных до 2 (т.е. будут базы 0 и 1).
# Это необязательно, т.к. по умолчанию и так есть база 0 и 1 (вместе с другими до 15).
# Но можем указать, чтобы явно только 0 и 1 существовали.
