apiVersion: v1
kind: Service
metadata:
  name: authservicekuber
spec:
  type: LoadBalancer
  selector:
    app: authservicekuber
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080